```{r}
library(tidyverse)
```

```{r}
teams <- read_csv("teams.csv")
#rosters1819 <- read_csv("rosters_2018-19.csv") |> select(-player_id)
#rosters1920 <- read_csv("rosters_2019-20.csv") |> select(-player_id)
rosters2021 <- read_csv("rosters_2020-21.csv") |> select(-player_id)
rosters2122 <- read_csv("rosters_2021-22.csv") |> select(-player_id)
rosters2223 <- read_csv("rosters_2022-23.csv") |> select(-player_id)
rosters2324 <- read_csv("rosters_2023-24.csv") |> select(-player_id)
rosters2425 <- read_csv("rosters_2024-25.csv") |> select(-player_id)

combined_rosters <- bind_rows(rosters2021, rosters2122, rosters2223, rosters2324, rosters2425)

players <- read_csv("players_with_ncaa_id.csv") 

```


```{r}
players |> 
  group_by(master_id) |> 
  summarize(teams = n()) |> 
  arrange(desc(teams))
```



```{r}

rosters2425 <- read_csv("rosters_2024-25.csv")
teams2425 <- rosters2425 %>% distinct(ncaa_id, team)
need_rosters <- teams %>% anti_join(teams2425, by='ncaa_id')

rosters2425 <- rosters2425 |> mutate(player_id = as.character(player_id))

roster_adds <- read_csv("adds.csv")


roster_adds <- roster_adds |> mutate(player_id = as.character(player_id), jersey = as.character(jersey))

rosters2425_with_adds <- bind_rows(rosters2425, roster_adds)


write_csv(rosters2425_with_adds,"rosters_2024-25.csv")

```


# Find missing values

```{r}
rosters2425 %>% filter(is.na(high_school))
rosters2425 %>% filter(is.na(position))
rosters2425 %>% filter(is.na(year))
rosters2425 %>% filter(is.na(height))
```



```{r}

rosters2223 <- read_csv("https://raw.githubusercontent.com/Sports-Roster-Data/womens-college-basketball/main/wbb_rosters_2022_23.csv")
rosters2324 <- read_csv("rosters_2023-24.csv")

teams2324 <- rosters2324 %>% distinct(ncaa_id, team)
need_rosters <- teams %>% anti_join(teams2324, by='ncaa_id')

rosters2324_with_teams <- rosters2324 %>% inner_join(teams, join_by(ncaa_id, team)) %>% select(-url.y, -stats_name, -twitter, -private)

acc_2324 <- rosters2324_with_teams %>% filter(conference == 'ACC')

write_csv(acc_2324, "acc_2324.csv")

rosters2324 %>% group_by(team) %>% summarize(players = n()) %>% arrange(players)
```


## Roster Continuity


```{r}
common_players_23 <- rosters2223 %>% inner_join(rosters2122, join_by(name, ncaa_id, team)) %>% 
  select(ncaa_id, team, name, year.x, url.x, year.y, url.y) %>% 
  mutate(previous_season = TRUE)

rosters2223 <- rosters2223 %>% left_join(common_players_23, join_by(url == url.x, ncaa_id == ncaa_id, team == team, name == name)) %>% mutate(previous_season = if_else(!is.na(previous_season), previous_season, FALSE)) %>% 
  select(ncaa_id, team, player_id, name, year, hometown, high_school, previous_school, height, position, jersey, url, season, previous_season)


common_players_22 <- rosters2122 %>% inner_join(rosters2021, join_by(name, ncaa_id, team)) %>% 
  select(ncaa_id, team, name, year.x, url.x, year.y, url.y) %>% 
   mutate(previous_season = TRUE)

rosters2122 <- rosters2122 %>% left_join(common_players_22, join_by(url == url.x, ncaa_id == ncaa_id, team == team, name == name)) %>% mutate(previous_season = if_else(!is.na(previous_season), previous_season, FALSE)) %>% 
  select(ncaa_id, team, player_id, name, year, hometown, high_school, previous_school, height, position, jersey, url, season, previous_season)

```


### NCAA IDs

```{r}
teams_with_ids <- read_csv("~/code/wbb/ncaa/stats/teams/teams_with_id_master.csv")
all_teams <- read_csv("~/code/wbb/ncaa/stats/ncaa_womens_basketball_teams.csv")

missing_team_stats <- all_teams |> anti_join(teams_with_ids, join_by(team_id==ncaa_id, season, url))

combined_teams <- all_teams |> inner_join(teams_with_ids, join_by(team_id==ncaa_id, season, url))

write_csv(combined_teams, "combined_teams.csv")

players_with_team_ids <- players |> inner_join(teams_with_ids, join_by(team_id == ncaa_id, season == season))
players |> anti_join(teams_with_ids, join_by(team_id == ncaa_id, season == season))

players_with_team_ids2 <- players |> inner_join(all_teams, join_by(season, team_id))

players |> anti_join(all_teams, join_by(season, team_id)) 


players25 <- players_with_team_ids |> filter(season == 2025)



rosters25_with_ids <- rosters2425 |> left_join(players25, join_by(ncaa_id == master_team_id, name == player_name))

unmatched_players25 <- rosters25_with_ids |> filter(is.na(season.y))

```

